rm:
  - id: rm
    ip: 127.0.0.1
    port: 5555
gfd:
  - id: gfd
    ip: 127.0.0.1
    port: 12345
servers:
  - id: S1
    ip: 127.0.0.1
    port: 7777
  - id: S2
    ip: 127.0.0.1
    port: 8888
  - id: S3
    ip: 127.0.0.1
    port: 9999
